//
//  ClipboardPrivacyTests.swift
//  pasterTests
//

import Testing
@testable import paster

struct ClipboardPrivacyTests {

    // MARK: Type-marker exclusion

    @Test("Confidential content is excluded")
    func confidentialTypeExcluded() {
        #expect(ClipboardPrivacy.isExcluded(types: ["org.nspasteboard.ConcealedType"]))
    }

    @Test("All transient markers are excluded, including the two pre-convention ones",
          arguments: ["org.nspasteboard.TransientType",
                      "org.nspasteboard.AutoGeneratedType",
                      "de.petermaurer.TransientPasteboardType",
                      "com.typeit4me.clipping"])
    func transientTypeExcluded(marker: String) {
        #expect(ClipboardPrivacy.isExcluded(types: [marker]))
    }

    @Test("A marker mixed in with ordinary types still excludes the whole clipping")
    func markerAmongOrdinaryTypes() {
        let types: Set<String> = ["public.utf8-plain-text",
                                  "public.html",
                                  "org.nspasteboard.ConcealedType"]
        #expect(ClipboardPrivacy.isExcluded(types: types))
    }

    @Test("Ordinary content is not excluded")
    func ordinaryNotExcluded() {
        #expect(!ClipboardPrivacy.isExcluded(types: ["public.utf8-plain-text", "public.rtf"]))
        #expect(!ClipboardPrivacy.isExcluded(types: []))
    }

    @Test("Universal Clipboard is read, not excluded — a clipping from the user's phone is one they want")
    func remoteClipboardNotExcluded() {
        #expect(!ClipboardPrivacy.isExcluded(types: [ClipboardPrivacy.remoteClipboardType]))
    }

    @Test("Office OLE types are a storage concern, not a privacy one, so they do not exclude the clipping")
    func oleTypesDoNotExcludeTheItem() {
        #expect(!ClipboardPrivacy.isExcluded(types: ["com.microsoft.ObjectLink"]))
        #expect(ClipboardPrivacy.nonStorableTypes.contains("com.microsoft.ObjectLink"))
    }

    // MARK: Password-manager app denylist

    @Test("Known password managers are blocked",
          arguments: ["com.agilebits.onepassword7",
                      "com.agilebits.onepassword-osx",
                      "com.1password.1password",
                      "com.bitwarden.desktop",
                      "com.lastpass.LastPass",
                      "com.dashlane.Dashlane",
                      "in.sinew.Enpass-Desktop",
                      "com.callpod.keepermac",
                      "com.apple.Passwords",
                      "com.apple.keychainaccess"])
    func passwordManagersBlocked(bundleID: String) {
        #expect(ClipboardPrivacy.isConfidentialApp(bundleID))
    }

    @Test("Matching is a substring test, so one entry survives a vendor shipping new bundle IDs")
    func substringMatchingCoversVariants() {
        // The reason this is not an exact-match list: 1Password alone has
        // shipped -osx, 4, 7 and 8.
        #expect(ClipboardPrivacy.isConfidentialApp("com.agilebits.onepassword4"))
        #expect(ClipboardPrivacy.isConfidentialApp("com.agilebits.onepassword8"))
        #expect(ClipboardPrivacy.isConfidentialApp("com.some.future.onepassword.variant"))
    }

    @Test("Matching ignores case")
    func matchingIsCaseInsensitive() {
        #expect(ClipboardPrivacy.isConfidentialApp("COM.BITWARDEN.DESKTOP"))
        #expect(ClipboardPrivacy.isConfidentialApp("Com.Apple.Passwords"))
    }

    @Test("Ordinary apps are allowed")
    func ordinaryAppsAllowed() {
        #expect(!ClipboardPrivacy.isConfidentialApp("com.apple.Safari"))
        #expect(!ClipboardPrivacy.isConfidentialApp("com.microsoft.VSCode"))
        #expect(!ClipboardPrivacy.isConfidentialApp(""))
    }

    // MARK: User exclusions

    @Test("A user exclusion blocks an app that is not built in")
    func userExclusionBlocks() {
        #expect(ClipboardPrivacy.isConfidentialApp("com.example.Notes",
                                                  userExcluded: ["com.example.notes"]))
    }

    @Test("User exclusions are additive — they cannot re-allow a built-in block")
    func userExclusionsCannotWeakenBuiltIns() {
        // The whole point of the built-in list: a preference that can switch
        // off password protection eventually gets switched off by accident.
        #expect(ClipboardPrivacy.isConfidentialApp("com.bitwarden.desktop", userExcluded: []))
        #expect(ClipboardPrivacy.isConfidentialApp("com.bitwarden.desktop",
                                                  userExcluded: ["something.else"]))
    }

    @Test("An empty user entry does not match everything")
    func emptyUserEntryMatchesNothing() {
        // A blank row in the settings list must not silently block all capture.
        #expect(!ClipboardPrivacy.isConfidentialApp("com.apple.Safari", userExcluded: [""]))
    }
}
