//
//  ClipboardPrivacy.swift
//  paster
//
//  Created by yinminqian on 21/8/2026.
//

import AppKit
import Foundation

/// What must never reach the store, and what is pointless to store.
///
/// Deliberately three separate lists rather than one, because they answer
/// different questions and deserve different trust levels: "is this a secret",
/// "is this throwaway", and "is this worth keeping". Collapsing them into a
/// single ignore list would mean a user relaxing one relaxes all of them.
enum ClipboardPrivacy {

    // MARK: Confidential

    /// A pasteboard carrying this is telling us it holds a secret.
    static let confidentialTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
    ]

    /// Substring tokens matched against the originating app's bundle
    /// identifier.
    ///
    /// This second layer exists because honouring `ConcealedType` alone is not
    /// enough — plenty of password managers never set it, so relying on other
    /// apps to behave correctly would leak their secrets into our history.
    ///
    /// Substring rather than exact match on purpose: vendors ship many bundle
    /// identifiers over time (1Password alone has shipped `-osx`, `4`, `7` and
    /// `8`), and an exact-match list silently rots into uselessness with every
    /// vendor release.
    static let confidentialAppTokens: [String] = [
        "com.apple.passwords",
        "com.apple.keychainaccess",
        "onepassword",
        "1password",
        "lastpass",
        "dashlane",
        "bitwarden",
        "enpass",
        "roboform",
        "keeper",
        "nordpass",
        "protonpass",
        "strongbox",
    ]

    // MARK: Transient

    /// A pasteboard carrying any of these is telling us the content is
    /// throwaway — a search field's live value, a macro expansion mid-flight.
    static let transientTypes: Set<String> = [
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        // The two pre-convention markers, from before the org.nspasteboard
        // namespace existed. Still emitted by older apps, and cheap to honour.
        "de.petermaurer.TransientPasteboardType",
        "com.typeit4me.clipping",
    ]

    // MARK: Not worth storing

    /// Excluded for uselessness, not privacy.
    ///
    /// Office puts OLE linkage blobs on the pasteboard that point at a live
    /// document session. They are large and they are meaningless the moment
    /// that session ends, so persisting them only bloats the store.
    static let nonStorableTypes: Set<String> = [
        "com.microsoft.ole.source",
        "com.microsoft.ObjectLink",
        "com.microsoft.Link-Source",
        "com.microsoft.DataObject",
    ]

    // MARK: Conventions we read rather than exclude

    /// Marks content that arrived from another device via Universal Clipboard.
    ///
    /// Read, not excluded: a clipping made on the user's phone is exactly the
    /// thing they want waiting for them here. It is only worth knowing about so
    /// the source can be labelled honestly, since the frontmost app did not
    /// produce it.
    static let remoteClipboardType = "com.apple.is-remote-clipboard"

    /// The convention's read-side courtesy: whoever wrote the pasteboard may
    /// name itself here. More trustworthy than the frontmost app when the write
    /// came from the background or from another device.
    static let sourceType = "org.nspasteboard.source"

    // MARK: Queries

    /// Whether content from this app must never be stored.
    ///
    /// `userExcluded` is additive: the built-in tokens stay in force whatever
    /// the user has configured, because a preference that can switch off
    /// password protection is a preference that eventually gets switched off by
    /// accident. Passed in rather than read from a global so the policy stays a
    /// pure function of its inputs.
    static func isConfidentialApp(_ bundleID: String, userExcluded: [String] = []) -> Bool {
        let normalized = bundleID.lowercased()
        if confidentialAppTokens.contains(where: normalized.contains) { return true }
        return userExcluded.contains { !$0.isEmpty && normalized.contains($0.lowercased()) }
    }

    /// Whether this set of pasteboard types means "do not record".
    static func isExcluded(types: Set<String>) -> Bool {
        !types.isDisjoint(with: confidentialTypes) || !types.isDisjoint(with: transientTypes)
    }
}
